spring:
  application:
    name: stockTrade

  devtools:
    restart:
      enabled: false
  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-cache: true
      static-locations: file:src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  task:
    scheduling:
      enabled: true

  freemarker:
    cache: false

  security:
    user:
      name: ADMIN
      password: 12345678

  datasource:
    url: jdbc:h2:file:~/stockTrade
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

hantu-openapi:
  appkey: #{appkey}
  appsecret: #{appsecret}
  appUrl: https://openapivts.koreainvestment.com:29443
  #appUrl: https://openapi.koreainvestment.com:9443 #실전 도메인
logging:
  level:
    org.hibernate.SQL: debug

kis:
  rank:
    refresh-interval-ms: 30000 # 30초마다 갱신

naver-openapi:
  clientId: #{clientId}
  clientSecret: #{clientSecret}

